### ISSUE TITLE
Status bar orientation

### ISSUE THREAD

**Issue by liken85** [terryworona/TWMessageBarManager#33]
Hi, similar to the given demo i have a view controller which only support portrait mode.

Before creating any message with TWMessageBarManager, the status bar does not rotate when the phone is in landscape mode.

![ios simulator screen shot apr 3 2014 6 19 28 pm](https://cloud.githubusercontent.com/assets/5058653/2602059/3e348764-bb1a-11e3-9048-27d282251d6b.png)

After creating a message with TWMessageBarManager, the status bar rotates when the phone rotates.

![ios simulator screen shot apr 3 2014 6 19 37 pm](https://cloud.githubusercontent.com/assets/5058653/2602118/f6dcba16-bb1a-11e3-9fc1-be5ef1643916.png)

Any idea how to fix this? The status bar shouldn't rotate when it is in landscape mode after displaying the message.

**Comment by skyylex** [comment]
Probably I've fixed this issue in https://github.com/terryworona/TWMessageBarManager/pull/67

**Comment by terryworona** [comment]
Fixed via #67
