### ISSUE TITLE
iOS 8 landscape orientation issue

### ISSUE THREAD

**Issue by ivanharmat** [terryworona/TWMessageBarManager#59]
How could this be fixed?
Messages work fine with portrait orientation, but they are either cut off (iPhone) or all over the screen (iPad). iOS 7 works like a charm, both orientations.
Thank you.

**Comment by miralmegha** [comment]
@PhillipApps Please replace orientFrame method  with this

- (CGRect)orientFrame:(CGRect)frame
{
	NSString *systemVersion = [UIDevice currentDevice].systemVersion;
	NSUInteger systemInt = [systemVersion intValue];
	
	if ( (UIDeviceOrientationIsLandscape([UIDevice currentDevice].orientation) || [UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationLandscapeLeft || [UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationLandscapeRight) && systemInt < 8 )
	{
		frame = CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height);
	}
	return frame;
}

frame = CGRectMake(frame.origin.x, frame.origin.y, frame.size.height, frame.size.width); in original code which should be like this

frame = CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height);

thanks
