### ISSUE TITLE
Use of [UIApplication sharedApplication]

### ISSUE THREAD

**Issue by mergesort** [terryworona/TWMessageBarManager#68]
TWMessageBarManager.m uses `[UIApplication sharedApplication].keyWindow.frame` to calculate the size of the message bar frame. The use of `[UIApplication sharedApplication]` means that this library can't be used in an extension. Would it be possible to optionally configure the frame externally?

Thanks a lot, love the library!

**Comment by terryworona** [comment]
Sorry, at this time you can't configure the message bar externally. 

Give it a shot and submit a PR! Love the username btw!
