### ISSUE TITLE
A way to hide a specific view

### ISSUE THREAD

**Issue by mergesort** [terryworona/TWMessageBarManager#69]
This would either entail external access to the `messageBarQueue`, or a facade, that lets you add tags of some sort to a `TWMessageView`, and be able to cancel a specific view.

There are times where I don't just want to show subsequent messages, but may want to cancel one.

@terryworona Do you have any thoughts, or ideas?

**Comment by terryworona** [comment]
Totally possible, but unlikely that it becomes a function in this library. 

Trying to keep it simple for now....
