### ISSUE TITLE
Implicit conversion from enumeration type 'UIInterfaceOrientation' (aka 'enum UIInterfaceOrientation') to different enumeration type 'UIDeviceOrientation' (aka 'enum UIDeviceOrientation')

### ISSUE THREAD

**Issue by ecnepsnai** [terryworona/TWMessageBarManager#71]
**I receive this warning in XCode:**

    TWMessageBarManager.m:728:112: Implicit conversion from enumeration type 'UIInterfaceOrientation' (aka 'enum UIInterfaceOrientation') to different enumeration type 'UIDeviceOrientation' (aka 'enum UIDeviceOrientation')

The class works fine, just get this warning when I build.  8.1SDK.

**Comment by terryworona** [comment]
Fixed via commit 581a116f5759f66f191218a99d669fb4db9678c3

**Comment by ecnepsnai** [comment]
Cool, thanks!  I've updated the class and will include it in the next update to my app.
