### ISSUE TITLE
Two large or wrongly positioned message on landscape iPad app with iOS 8

### ISSUE THREAD

**Issue by centurionas** [terryworona/TWMessageBarManager#73]
Message is shown of full screen iPad portrait size on iPad landscape app with iOS 8. Tried with iPad 2 (iOS 8) simulator.  Success message type. I didn't find any info about it being not supported for iPad, therefore wondering has anybody tried it to use on iPad?

**Comment by centurionas** [comment]
Now it works. Used @ivanharmat suggested fix: https://github.com/terryworona/TWMessageBarManager/issues/59

**Comment by centurionas** [comment]
It would be nice this fix to be merged into regular branch.

**Comment by terryworona** [comment]
@centurionas you want to submit a PR for this fix?

**Comment by terryworona** [comment]
Pulled in this manually via commit: 581a116f5759f66f191218a99d669fb4db9678c3

**Comment by centurionas** [comment]
Thanks @terryworona for excellent library. Now it works. Though I'm wondering why it's showing 1.7.2 version in cocoa pods and my pods file contains "pod 'TWMessageBarManager', '~> 1.7'". But when I run pod install it's written "Installing TWMessageBarManager 1.7.0 (was 1.7.0)".

**Comment by cdzombak** [comment]
> Though I'm wondering why it's showing 1.7.2 version in cocoa pods and my pods file contains "pod 'TWMessageBarManager', '~> 1.7'". But when I run pod install it's written "Installing TWMessageBarManager 1.7.0 (was 1.7.0)". Should it be saying "1.7.2" when installing pod?

What's in your `Podfile.lock`? If you have previously installed 1.7.0, `pod install` won't update it for you—either change your `Podfile` to require `pod 'TWMessageBarManager', '~> 1.7.2'` or run `pod update`.

**Comment by terryworona** [comment]
@centurionas - change your podfile to:

    pod 'TWMessageBarManager'

or

    pod 'TWMessageBarManager', '~> 1.7.2'
