### ISSUE TITLE
please update your cocoapods

### ISSUE THREAD

**Issue by lunarbase** [terryworona/TWMessageBarManager#74]
Please update your cocoapods.org implementation. It is downloading the old version of this class.
thanks.

**Comment by terryworona** [comment]
The cocoapods repository is up to date: https://cocoapods.org/pods/TWMessageBarManager

The latest version is [v1.7.2](https://github.com/terryworona/TWMessageBarManager/tree/v1.7.2)

I created a shell project to test this with the following podfile:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    pod 'TWMessageBarManager'

Installation was successful:

    Analyzing dependencies
    CocoaPods 0.36.3 is available.
    To update use: `gem install cocoapods`
    For more information see http://blog.cocoapods.org
    and the CHANGELOG for this version http://git.io/BaH8pQ.
    Downloading dependencies
    Installing TWMessageBarManager (1.7.2)
    Generating Pods project
    Integrating client project
