### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by KBLNY** [terryworona/TWMessageBarManager#80]
Hey, 

Thanks for your work, it's so great!! However, I'm still striving by using my custom protocol.

How Am I supposed to use when I call showMessageWithTitle?

Thanks for your help

**Comment by terryworona** [comment]
I don't understand the question.

     I'm still striving by using my custom protocol

Please elaborate?

**Comment by KBLNY** [comment]
I implemented "An object conforming to the TWMessageBarStyleSheet protocol defines the message bar's look and feel:" with the 3 required methods:
- (UIColor *)backgroundColorForMessageType:(TWMessageBarMessageType)type;
- (UIColor *)strokeColorForMessageType:(TWMessageBarMessageType)type;
- (UIImage *)iconImageForMessageType:(TWMessageBarMessageType)type;

However, I don't know how I should use this implementation.
Can you help?

**Comment by terryworona** [comment]
Set the manager singleton's sharedInstance stylesheet property:

    [TWMessageBarManager sharedInstance].styleSheet = yourCustomStyleSheet;

**Comment by KBLNY** [comment]
Ok, but what should I put as value for the parameter "type" when I use the showMessageWithTitle: method?

**Comment by terryworona** [comment]
I message bar type: TWMessageBarMessageTypeError, TWMessageBarMessageTypeSuccess or TWMessageBarMessageTypeInfo. 

Closing this question. 

Please read the documentation or play with the demo application bundled with the library to learn more.

**Comment by KBLNY** [comment]
Ok, thanks it works !

I read the documentation and I played with the demo.
But it sounds weird for me, when you specified a custom stylesheet that you have to choose a default bar type (Info, Success or Error) which will be ignored, since I have specified my own stylesheet.

In addition, how can I use a second stylesheet? At the end, I would have something like : Error, Info, Success, Critical (1st custom stylesheet) and "Push Notification" (2nd custom stylesheet).
