### ISSUE TITLE
Swift Project

### ISSUE THREAD

**Issue by UtkuDalmaz** [terryworona/TWMessageBarManager#90]
How can i use this library in a swift project ?

**Comment by terryworona** [comment]
The same as you would any project that mixes Swift and Objective C. 

See here https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html.

**Comment by UtkuDalmaz** [comment]
Ok one question
How can i handle the touch on alert ?
