### ISSUE TITLE
use_frameworks!

### ISSUE THREAD

**Issue by gask** [terryworona/TWMessageBarManager#93]
When I put "use_frameworks!" in my podfile due to other pods, TWMessageBarManager starts giving errors, not being recognized.

**Comment by terryworona** [comment]
This could be caused by any number of things. Please provide specifics such as stack traces or log files. 

Are you sure you're opening the workspace file instead of the xcodeproject?

**Comment by gask** [comment]
Yes, I'm sure.

Here's the stack:
`/Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/DjengoApp/MobicityApp-Bridging-Header.h:10:9: note: in file included from /Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/DjengoApp/MobicityApp-Bridging-Header.h:10:
#import "ChatService.h"
        ^
/Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/DjengoApp/ChatService.h:10:9: note: in file included from /Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/DjengoApp/ChatService.h:10:
#import "SSUUserCache.h"
        ^
/Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/DjengoApp/SSUUserCache.h:12:9: error: 'TWMessageBarManager.h' file not found
#import "TWMessageBarManager.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/DjengoApp/MobicityApp-Bridging-Header.h'`

I had to manually add a user header search path to Pods/*\* to stop the errors.
And another thing I noted: this only happens when I archive the product. When I build & run no errors are given.

Any clues?

**Comment by terryworona** [comment]
Your bridging header looks mis-configured. TWMessageBarManager is not the first class that appears to be missing - they all are, starting @ ChatService.h. 

No other ideas, it's unlikely an issue with TWMessageBarManager and more-so with your project structure. I would check stack threads for "Bridging header missing file' or something to that effect.

**Comment by gask** [comment]
@terryworona After lots of hours working on this I manager to solve this by adding
`#import <TWMessageBarManager/TWMessageBarManager-umbrella.h>`
to my Objective-C files that used TWM, because they didn't recognize the TWMessageBarManager.h...
I commented out the import from the bridging header and voilà!
